import { BarChartCard } from '@/components/charts/BarChartCard';
import { DonutChartCard } from '@/components/charts/DonutChartCard';
import { LineChartCard } from '@/components/charts/LineChartCard';
import { FeatureCard } from '@/components/cards/FeatureCard';
import { ResultSummaryCard } from '@/components/cards/ResultSummaryCard';
import { StatCard } from '@/components/cards/StatCard';
import { DashboardShell } from '@/components/layout/DashboardShell';
import { statusBadge } from '@/components/ui/Badge';
import {
  certTrend,
  examDonut,
  kpiStats,
  platformFeatures,
  recentRecords,
  reportsGeneratedByMonth,
  resultGenDonut,
  resultGenSummary,
  roleDistribution,
  roleDistributionColors,
  surveyDataSubmissions,
} from '@/data/mockDashboard';

function formatDateTime(iso: string) {
  const date = new Date(iso);
  return `${date.toLocaleDateString('en-NG', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  })} ${date.toLocaleTimeString('en-NG', {
    hour: '2-digit',
    minute: '2-digit',
  })}`;
}

export default function DashboardPage() {
  return (
    <DashboardShell pageTitle="Dashboard">
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4 2xl:grid-cols-8">
        {kpiStats.map((stat) => (
          <StatCard key={stat.label} {...stat} />
        ))}
      </div>

      <div className="mt-5 grid grid-cols-1 gap-4 xl:grid-cols-3">
        <LineChartCard
          title="Certification Trends"
          data={certTrend}
          series={[{ key: 'issued', color: '#15803d', label: 'Certifications Issued' }]}
        />
        <DonutChartCard
          title="Examination Performance"
          data={examDonut}
          centerLabel="15,389"
          centerSubLabel="Total Records"
          colors={['#16a34a', '#2563eb', '#f59e0b', '#ef4444']}
        />
        <DonutChartCard
          title="Role-Based Access Overview"
          data={roleDistribution}
          centerLabel="128"
          centerSubLabel="Total Users"
          colors={roleDistributionColors}
        />
      </div>

      <div className="mt-4 grid grid-cols-1 gap-4 xl:grid-cols-3">
        <BarChartCard
          title="Survey Data Submissions"
          data={surveyDataSubmissions}
          series={[{ key: 'submissions', color: '#16a34a', label: 'Submissions' }]}
        />
        <DonutChartCard
          title="Result Generation Summary"
          data={resultGenDonut}
          centerLabel="1,320"
          centerSubLabel="Results"
          colors={['#16a34a', '#f59e0b', '#ef4444']}
        />
        <FeatureCard features={platformFeatures} />
      </div>

      <div className="mt-4 grid grid-cols-1 gap-4 xl:grid-cols-3">
        <div className="xl:col-span-2">
          <ResultSummaryCard {...resultGenSummary} />
        </div>
        <BarChartCard
          title="Reports Generated by Month"
          data={reportsGeneratedByMonth}
          series={[{ key: 'reports', color: '#0f766e', label: 'Reports Generated' }]}
        />
      </div>

      <div className="mt-5 rounded-xl border border-slate-200 bg-white shadow-sm">
        <div className="flex items-center justify-between border-b border-slate-200 px-5 py-4">
          <h3 className="text-base font-bold text-slate-900">Recent Activity / Recent Records</h3>
          <a
            href="/examinations"
            className="rounded-md border border-emerald-600 px-3 py-1.5 text-xs font-semibold text-emerald-700 hover:bg-emerald-50"
          >
            View All Records
          </a>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full min-w-[980px] border-separate border-spacing-0">
            <thead>
              <tr>
                {[
                  'Candidate / Surveyor Name',
                  'Registration No.',
                  'Record Type',
                  'Examination Status',
                  'Score',
                  'Certification Status',
                  'Date',
                ].map((heading) => (
                  <th
                    key={heading}
                    className="border-b border-slate-200 bg-slate-50 px-4 py-3 text-left text-xs font-bold text-slate-700"
                  >
                    {heading}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {recentRecords.map((record) => (
                <tr key={record.regNo} className="hover:bg-slate-50">
                  <td className="border-b border-slate-100 px-4 py-3">
                    <div className="flex items-center gap-3">
                      <span className="flex h-7 w-7 items-center justify-center rounded-full bg-emerald-700 text-xs font-bold text-white">
                        {record.name.charAt(0)}
                      </span>
                      <span className="text-sm font-semibold text-slate-800">{record.name}</span>
                    </div>
                  </td>
                  <td className="border-b border-slate-100 px-4 py-3 font-mono text-xs text-slate-600">{record.regNo}</td>
                  <td className="border-b border-slate-100 px-4 py-3 text-sm text-slate-700">{record.recordType}</td>
                  <td className="border-b border-slate-100 px-4 py-3">{statusBadge(record.examStatus)}</td>
                  <td className="border-b border-slate-100 px-4 py-3 text-sm font-bold text-slate-800">{record.score}</td>
                  <td className="border-b border-slate-100 px-4 py-3">{statusBadge(record.certStatus)}</td>
                  <td className="border-b border-slate-100 px-4 py-3 text-xs text-slate-500">{formatDateTime(record.date)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </DashboardShell>
  );
}
